export const indexData_7 = [
  { title: "夏侯生莲", pr: 3.0 },
  { title: "夏侯生莲(动态)", pr: 2.0 },
  { title: "步步折桂", pr: 3.0 },
  { title: "步步折桂(动态)", pr: 2.0 },
  { title: "并蒂睡莲", pr: 3.0 },
  { title: "并蒂睡莲(动态)", pr: 3.0 },
  { title: "丹桂飘香", pr: 2.0 },
  { title: "丹桂飘香(动态)", pr: 3.0 },
  { title: "水佩争妍", pr: 2.0 },
  { title: "桂馥兰香", pr: 3.0 },
  { title: "白露吴国太", pr: 4.0 },
  { title: "孔融让梨", pr: 4.0 },
  { title: "白露边框", pr: 4.0 },
  { title: "一叶知秋", pr: 4.0 },
  { title: "露凝而白", pr: 4.0 },
  { title: "秋叶满树", pr: 4.0 },
  { title: "经典版庞德", pr: 8.0 },
  { title: "经典版庞统", pr: 8.0 },
  { title: "夏日神周", pr: 5.0 },
  { title: "夏日曹丕", pr: 5.0 },
  { title: "天秤孙权", pr: 4.0 },
  { title: "处女周瑜", pr: 4.0 },
  { title: "天秤边框", pr: 4.0 },
  { title: "处女边框", pr: 4.0 },
  { title: "天秤星座", pr: 4.0 },
  { title: "处女星座", pr: 4.0 }
];
