// 芍药昙花
export const indexData_8 = [
  { title: "昙花一现(动态)", pr: 2.0 },
  { title: "花间秋千(动态)", pr: 2.0 },
  { title: "寂寂昙花(动态)", pr: 2.0 },
  { title: "翠茎红蕊(动态)", pr: 2.0 },
  { title: "昙花一现", pr: 4.0 },
  { title: "花间秋千", pr: 4.0 },
  { title: "寂寂昙花", pr: 4.0 },
  { title: "翠茎红蕊", pr: 4.0 },
  { title: "亭台初夏", pr: 2.0 },
  { title: "荼蘼芍药", pr: 2.0 },
  { title: "霜露异彩", pr: 3.0 },
  { title: "冰雪女神", pr: 3.0 },
  { title: " 寒露润物", pr: 3.0 },
  { title: "傲雪凌霜", pr: 3.0 },
  { title: "寒露凝秋", pr: 3.0 },
  { title: "凝露成霜", pr: 3.0 },
  { title: "采荷诸葛果", pr: 6.0 },
  { title: "元宵董白", pr: 6.0 },
  { title: "泳装文姬", pr: 6.0 },
  { title: "悠然南山", pr: 6.0 },
  { title: "碧海云天", pr: 6.0 },
  { title: "电雷石火", pr: 6.0 },
  { title: "白釉青花", pr: 6.0 },
  { title: "繁华似锦", pr: 6.0 },
  { title: "和和美美", pr: 6.0 }
];
