export const indexData_6 = [
  { title: "茉莉小乔", pr: 3.0 },
  { title: "茉莉小乔(动态)", pr: 2.0 },
  { title: "天赋仙姿", pr: 3.0 },
  { title: "天赋仙姿(动态)", pr: 2.0 },
  { title: " 洁白淡雅", pr: 3.0 },
  { title: "冰清徐氏", pr: 3.0 },
  { title: "冰清徐氏(动态)", pr: 2.0 },
  { title: "皎洁玉兰", pr: 3.0 },
  { title: "皎洁玉兰(动态)", pr: 2.0 },
  { title: "次韵玉兰", pr: 3.0 },
  { title: "立秋步练师", pr: 3.0 },
  { title: "曹植放灯", pr: 3.0 },
  { title: "落叶瑟瑟", pr: 3.0 },
  { title: "环龙玉佩", pr: 3.0 },
  { title: "树树秋声", pr: 3.0 },
  { title: "荷花灯河", pr: 3.0 },
  { title: "经典版孟获", pr: 8.0 },
  { title: "经典版祝融", pr: 8.0 },
  { title: "作业如山(动态)", pr: 8.0 },
  { title: "旗帜摇曳(动态)", pr: 8.0 },
  { title: "白釉青花", pr: 8.0 },
  { title: "春水溪桥", pr: 8.0 },
  { title: "月明星稀", pr: 8.0 },
  { title: "墨亭柳岸", pr: 8.0 }
];
