export const indexData_5 = [
  { title: "鸢尾春华", pr: 3.0 },
  { title: "鸢尾春华(动态)", pr: 2.0 },
  { title: "清雅鸢尾", pr: 3.0 },
  { title: "清雅鸢尾(动态)", pr: 2.0 },
  { title: "水趣鸢尾", pr: 3.0 },
  { title: "木兰王异", pr: 3.0 },
  { title: "木兰王异(动态)", pr: 2.0 },
  { title: "木末芙蓉", pr: 3.0 },
  { title: "木末芙蓉(动态)", pr: 2.0 },
  { title: "辛夷花白", pr: 3.0 },
  { title: "金芒圣光", pr: 6.0 },
  { title: "水中掠影", pr: 6.0 },
  { title: "亭亭玉立", pr: 6.0 },
  { title: "暗火边框", pr: 6.0 },
  { title: "经典版卧龙", pr: 6.0 },
  { title: "宅男赵云", pr: 6.0 },
  { title: "经典版荀彧", pr: 6.0 },
  { title: "恋枫刘备", pr: 6.0 },
  { title: "恋枫刘备(动态)", pr: 3.0 },
  { title: "恋枫尚香", pr: 6.0 },
  { title: "恋枫尚香(动态)", pr: 3.0 },
  { title: "枫叶流丹", pr: 6.0 },
  { title: "枫叶流丹(动态)", pr: 3.0 },
  { title: "山林狭径", pr: 5.0 }
];
